### ISSUE TITLE
Branch Management

### ISSUE THREAD

**Issue by JWLeRoi** [WebDevBootcamp/hatsallfolks#11]
The branch named "Brad" is redundant. Doesn't look like there would be any problem in deleting it. Any  objections?

**Comment by BradAyers** [comment]
No objections here.  I think you're liking the "issues" button (LOL).  I'm
going to spend a few more moments now working on the PHP code for your AJAX
calls.  If you need to touch base with me this weekend, feel free to call
or text.  I'm going to be pretty much in and out as my wife and I work on
the first push for our move this month.  Have a great day and enjoy the
sunshine while it's still out.

On Sat, May 16, 2015 at 10:05 AM, Jack LeRoi notifications@github.com
wrote:

> The branch named "Brad" is redundant. Doesn't look like there would be any
> problem in deleting it. Any objections?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebDevBootcamp/hatsallfolks/issues/11.

## 

Brad Ayers
303-588-6397 cell
Brad@AyersKin.com

**Comment by JWLeRoi** [comment]
OK. I deleted the branch.

**Comment by BradAyers** [comment]
OK Jack.  I just updated the thumbs.php in our "includes" directory for the
AJAX call.  It's on my git branch.  Give it a shot and hopefully it works.
I concatenated the sku, product and description to build the $items array
and I am not sure that JSON will like that.  Let me know if this is a
problem and I can restructure the array if needed.  Talk to you soon.

On Sat, May 16, 2015 at 11:32 AM, Jack LeRoi notifications@github.com
wrote:

> OK. I deleted the branch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebDevBootcamp/hatsallfolks/issues/11#issuecomment-102657631
> .

## 

Brad Ayers
303-588-6397 cell
Brad@AyersKin.com
