### ISSUE TITLE
ARRAY...not STRING

### ISSUE THREAD

**Issue by BradAyers** [WebDevBootcamp/hatsallfolks#12]
Hey Jack.  I just realized that the concatenation is still creating a string.  I know that you need an array so that JSON can parse the object.  Sorry about that.  I'm about to go mow the lawn and I will change the code after that so that the return will render an array.

**Comment by JWLeRoi** [comment]
HI, Brad,
I checked out the thumbs.php and it's producing like this:

Array
(
    [0] => 01-12345-01,Panama,This one is nice!
    [1] => 01-22345-01,Porkpie,Very porky
    [2] => 01-32345-01,Fedora,Feds love these
    [3] => 01-42345-01,Sunhat,Keeps you shady
    [4] => 01-52345-01,Derby,Great at the races
    [5] => 01-12345-02,Panama,This one is nice!
)

It needs to be producing like this:

[{"sku":"01-12345-01","product":"Panama","description":"This one is nice!"},{"sku":"01-22345-01","product":"Porkpie","description":"Very porky"},{"sku":"01-32345-01","product":"Fedora","description":"Feds love these"},{"sku":"01-42345-01","product":"Sunhat","description":"Keeps you shady"},{"sku":"01-52345-01","product":"Derby","description":"Great at the races"},{"sku":"01-12345-02","product":"Panama","description":"This one is nice!"}]

Thanks!!

**Comment by JWLeRoi** [comment]
Hi, Brad,
 I modified the thumbs.php file to produce the right return. The code is like this:

<?php
    include('includes/db.php');
    $conn = db_connect();

```
// QUERY DB FOR SMALL SIZES ONLY SO THAT MAIN PAGE SHOWS ONLY EACH PRODUCT, NOT SIZES AND COLORS
$sql = "SELECT sku, product, description FROM Inventory WHERE size='small'";
$result = $conn->query($sql);
$conn->close();

if ($result->num_rows > 0)
{
  $items = [];
  // OUTPUT DATA FOR EACH ROW
  while($row = $result->fetch_assoc())
  {

      $items[] = $row;
  }
}
else
{
     echo "0 results";
}

print json_encode($items);
```

?>

It works OK but it still produces a duplicate thumbnail. Could you please a look at what needs to be done to fix that?

Thanks a lot!

**Comment by JWLeRoi** [comment]
Initial project prototype was presented successfully at graduation
