### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by JWLeRoi** [WebDevBootcamp/hatsallfolks#4]
What browser types are we going to characterize for? There's also the question of the HTML/CSS level.

**Comment by mikeyoutz** [comment]
How about Chrome, Safari and Firefox... with graceful fail on IE. What were you thinking Jack?

As for the HTML/CSS level... I'm thinking HTML 5 and some CSS that is well supported ( (not Flexbox). 

Are my answers too general?

**Comment by JWLeRoi** [comment]
Sounds reasonable to me. Here's another question. Do we gain more if we choose one browser and spend time adding features, or if we spend the time making things work with more than one browser? I've done everything so far for Chrome so I don't have a good handle on how much extra time it would take for more than one. Maybe Nathan or Ben can comment.
@nw 
@guyjin

**Comment by nw** [comment]
As long as your not going exotic with features you really shouldn't have an issue. When you add something maybe test at that point.

Generally it's not that big of a deal. I usually build for one browser and add a few compatibility fixes at the end

**Comment by BradAyers** [comment]
Thanks Nate. That sounds good to me.

Brad Ayers
303.588.6397
Brad@AyersKin.com
