### ISSUE TITLE
Branch Management

### ISSUE THREAD

**Issue by JWLeRoi** [WebDevBootcamp/hatsallfolks#5]
@mike
@nw
@guyjin 
I own the mike branch because I created it. Is there a good reason to delete it and have Mike create one he owns?

**Comment by nw** [comment]
You all "own" it. The point of branches is containment not permissions.

I'm almost done with a really good doc to explain this in a simplified
visual manner, stay tuned!

**Comment by JWLeRoi** [comment]
Most excellent! I think I could use that. Something blew up on me when I cloned/branched/pushed/whatever. I tried to use JQuery but it doesn't recognize it. I have the same script tag as with the projects where it works. I think I'm going to delete the branches I made and start over.
