### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by JWLeRoi** [WebDevBootcamp/hatsallfolks#9]
Error message on ajax call is "Class 'mysqli' not found in jack\includes\db.php on line 8".

**Comment by JWLeRoi** [comment]
The web server in the IntelliJ IDE doesn't have mysqli enabled. Uploaded files to weblab.us. Call succeeds now.

**Comment by BradAyers** [comment]
Thanks for the update. I'll get the detailed SQL call to you soon then
start working on our cart.

Brad Ayers
303.588.6397
Brad@AyersKin.com
